name: PDF Bibliography action
description: Checks the reference list of a PDF on PRs
inputs:
  token:
    description: Token for GitHub API requests
    required: true
    default: ${{ github.token }}
  repo_path:
    required: true
    default: './'
  repo_name:
    required: true
  pr_number: 
    required: true
  verbosity:
    description: Level of verbosity when prettifying references 
    required: true
    default: 2
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo_path }}
    - ${{ inputs.token }}
    - ${{ inputs.repo_name }}
    - ${{ inputs.pr_number }}
    - ${{ inputs.verbosity }}